# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Users:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [db_provider, in_memory]

        db_provider:
            entity:
                class: AppBundle:Users
                property: username

        in_memory:
            memory:
                users:
                    guest: 
                        password: password
                        roles: 'ROLE_GUEST'

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/admin, roles: [ROLE_GUEST, ROLE_ADMIN] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            #http_basic: ~
            anonymous: ~
            pattern: ^/
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: '_username'
                default_target_path: admin_projects_index
            logout: 
                path: /logout
                target: /login
